import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import sveltePlugin from "esbuild-svelte"; // Added
import sveltePreprocess from "svelte-preprocess"; // Added

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
IF YOU WANT TO VIEW THE SOURCE CODE, GO TO THE GIT REPO AND PULLED THE LATEST VERSION
(https://github.com/nicsaiart1/obsidian-life-planner-plugin)
*/
`;

const prod = process.argv[2] === "production";

esbuild
  .build({
    banner: {
      js: banner,
    },
    entryPoints: ["main.ts"], // Potentially add Svelte components if they are main entry points, though usually imported by TS
    bundle: true,
    external: [ // Ensure this list is maintained from previous steps
      "obsidian",
      "electron",
      "@codemirror/autocomplete",
      "@codemirror/collab",
      "@codemirror/commands",
      "@codemirror/language",
      "@codemirror/lint",
      "@codemirror/search",
      "@codemirror/state",
      "@codemirror/view",
      "@lezer/common",
      "@lezer/highlight",
      "@lezer/lr",
      ...builtins,
    ],
    format: "cjs",
    watch: !prod,
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    plugins: [ // Added sveltePlugin
      sveltePlugin({
        preprocess: sveltePreprocess(),
      })
    ],
  })
  .catch(() => process.exit(1));
